### ISSUE TITLE
Create more than one period with data, check for Functional correctness of application .

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/HPMS#1]
- [x] Integration module must be updated : Get active period and unit index group and job index groups by Active period for more than one period ( period create by end user) 
- [x]  @SaeidBarzegar Check for duplicate insertion in basicInformation by transferId from integration transformation 
- [x] Do all step for two period for check other things

**Comment by SaeidBarzegar** [comment]
Unit Index duplicate checking is ready but must implement API For the service wrapper.
