### ISSUE TITLE
Create Employee point report 

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/HPMS#45]
[EmployeePerformanceResultSheet.pdf](https://github.com/ehsmohammadi/HPMS/files/533452/EmployeePerformanceResultSheet.pdf)

Employee point must show as level : 
if point is in this range ( 90>= point <= 100 ) => Excellent ( عالی ) 
if point is in this range ( 70>= point < 90) => Good( خوب) 
if point is in this range ( 50>= point < 70) => Acceptable ( قابل قبول) 
if point is in this range ( 30>= point < 50) => Need training ( نیاز به آموزش) 
if point is in this range ( 30>= point < 50) => Bad ( نا مطلوب)

**Comment by SaeidBarzegar** [comment]
We must change weak point from (X<50) to (X<30) and also good point from (X>=80) to (X>=90)

**Comment by SaeidBarzegar** [comment]
Edited titles and ranges.

**Comment by ehsmohammadi** [comment]
Ms.Mousavi has changed : 
 1 .Increase  font size 
2 .امتیاز کل  must changed to سطح عملکرد
3. Remove unit point title and all of it ... 
4.  Bold the box that employee point was shown in it . 
5.  Centralize the strength part title

**Comment by ehsmohammadi** [comment]
All changed had been performed ...

**Comment by ehsmohammadi** [comment]
[بسمه تعالی.docx](https://github.com/ehsmohammadi/HPMS/files/549921/default.docx)

Add the above help text for employee result page

**Comment by ehsmohammadi** [comment]
The requested description was inserted in the employee result page and all thing in order now.
