### ISSUE TITLE
Create unit manager report

### ISSUE THREAD

**Issue by SaeidBarzegar** [ehsmohammadi/HPMS#46]
[ResultSheetForUnitManager.pdf](https://github.com/ehsmohammadi/HPMS/files/499986/ResultSheetForUnitManager.pdf)
- The employee that we show their points to their manager should be selected from related direct below person in organization chart 
- Like all other result view we don't show the number of employee point , and its like the inquiry form for employee we show their result

**Comment by SaeidBarzegar** [comment]
We have some problems with sql server version on my pc and it makes me to remove my sql 2014 and also sql express 2012 and reinstall sql server 2014.
It take one day!! (with supporting hoopad food system by get remote and try to solve the problem.)

**Comment by ehsmohammadi** [comment]
After checking all requirement for doing this task  we must doing this tasks : 
Create UI view 
Create UI business logic

**Comment by ehsmohammadi** [comment]
- Manager result view has problem , strengths point and weak point was not base on average index point 
- check if employee No was not in our system 
- character between two job position or unit  needed

**Comment by ehsmohammadi** [comment]
All thing in order now , i will publish the application

**Comment by ehsmohammadi** [comment]
application was published
